# Generated by Django 3.2.4 on 2021-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210713_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='tmu_logo.jpg', upload_to='profile_pics/'),
        ),
    ]
